Repository Swyp-team10/molip-backend, pull requests merged in 2024-07, with the labels that each got.

#7 Feat : 카카오 소셜 로그인 오류 상황별 응답 메시지 수정 및 User 엔티티에 성별과 나이 컬럼 추가
  src/main/java/org/example/shallweeatbackend/constant/Gender.java
  src/main/java/org/example/shallweeatbackend/entity/User.java
  src/main/java/org/example/shallweeatbackend/filter/CustomLogoutFilter.java
  src/main/java/org/example/shallweeatbackend/filter/JWTFilter.java
  src/main/java/org/example/shallweeatbackend/service/ReissueTokenService.java
Labels: feature

#8 Fix : 응답 메시지 인코딩 문제 수정
  src/main/java/org/example/shallweeatbackend/filter/CustomLogoutFilter.java
  src/main/java/org/example/shallweeatbackend/filter/JWTFilter.java
  src/main/java/org/example/shallweeatbackend/service/ReissueTokenService.java
Labels: bug

#10 Fix : CORS 관련 설정 수정
  src/main/java/org/example/shallweeatbackend/config/CorsMvcConfig.java
  src/main/java/org/example/shallweeatbackend/config/SecurityConfig.java
Labels: bug

#11 Fix : CORS 설정 수정, 로그인 성공 후 리다이렉트 추가 및 토큰 처리 로직 수정
  src/main/java/org/example/shallweeatbackend/config/CorsMvcConfig.java
  src/main/java/org/example/shallweeatbackend/config/CustomSuccessHandler.java
  src/main/java/org/example/shallweeatbackend/config/SecurityConfig.java
  src/main/java/org/example/shallweeatbackend/service/ReissueTokenService.java
Labels: bug

#12 Feat : 개인 메뉴판 관련 CRUD 기능 구현
  src/main/java/org/example/shallweeatbackend/controller/PersonalBoardController.java
  src/main/java/org/example/shallweeatbackend/dto/PersonalBoardDTO.java
  src/main/java/org/example/shallweeatbackend/dto/RecommendMenuDTO.java
  src/main/java/org/example/shallweeatbackend/dto/RecommendOptionsDTO.java
  src/main/java/org/example/shallweeatbackend/entity/Menu.java
  src/main/java/org/example/shallweeatbackend/entity/MenuTag.java
  src/main/java/org/example/shallweeatbackend/entity/PersonalBoard.java
  src/main/java/org/example/shallweeatbackend/entity/PersonalBoardMenu.java
  src/main/java/org/example/shallweeatbackend/entity/Tag.java
  src/main/java/org/example/shallweeatbackend/entity/User.java
  src/main/java/org/example/shallweeatbackend/exception/PersonalBoardNotFoundException.java
  src/main/java/org/example/shallweeatbackend/repository/MenuRepository.java
  src/main/java/org/example/shallweeatbackend/repository/MenuTagRepository.java
  src/main/java/org/example/shallweeatbackend/repository/PersonalBoardMenuRepository.java
  src/main/java/org/example/shallweeatbackend/repository/PersonalBoardRepository.java
  src/main/java/org/example/shallweeatbackend/repository/TagRepository.java
  src/main/java/org/example/shallweeatbackend/service/PersonalBoardService.java
Labels: feature

#14 Feat : 메뉴판 삭제 시 응답 메시지 추가
  src/main/java/org/example/shallweeatbackend/controller/PersonalBoardController.java
  src/main/java/org/example/shallweeatbackend/service/PersonalBoardService.java
Labels: feature

#20 Feat : HTTPS 리디렉션 추가 및 keystore 파일 무시 설정
  .gitignore
  src/main/java/org/example/shallweeatbackend/config/SecurityConfig.java
Labels: feature

#64 Feature/team fix
  src/main/java/org/example/shallweeatbackend/dto/TeamBoardListDTO.java
  src/main/java/org/example/shallweeatbackend/repository/TeamBoardMenuRepository.java
  src/main/java/org/example/shallweeatbackend/service/TeamBoardMenuService.java
  src/main/java/org/example/shallweeatbackend/service/TeamBoardService.java
Labels: enhancement
